### ISSUE TITLE
Abbreviations in Quick Add

### ISSUE THREAD

**Issue by amazansky** [MyHomeworkSpace/client#126] opened 2020-04-27 02:30 UTC
## Classes
Currently, Quick Add recognizes abbreviations such as **chem** for Chemistry, but should be expanded to include other common abbreviations like **ush** for "US History", **span** for Spanish, etc.

Alternatively/additionally, we could let the user define one or multiple shortcuts for each class in classes settings so they can just do it themselves.

## Dates
Some ideas:
- **tom**/**tmr**/**tmrw** to Tomorrow
- **tue** to Tuesday and **thu** to Thursday, instead of the current **tues** and **thurs**

**Comment by thatoddmailbox** [comment] 2020-04-27 02:37
I added the specific class abbreviations you mentioned, and I'll add the date abbreviations. However, like you said, I think ultimately the way to go is allowing users to define synonyms for classes they create.

**Comment by thatoddmailbox** [comment] 2020-04-27 02:48
I didn't add "tom" as an abbreviation because I thought it would conflict with the actual name Tom, in case someone tried to add something like "meet with tom" to their calendar. I'm not sure if there's a smart way of resolving that...maybe checking for a structure like "due tom" or "by tom"?

**Comment by thatoddmailbox** [comment] 2020-04-27 05:21
I think the class synonym stuff is a duplicate of #118. Since everything else in this issue was added, I'm going to close it, but if I missed something, just let me know.

**Closed by thatoddmailbox** 2020-04-27 05:21 UTC
Labels: enhancement
